# On pourrait utiliser curl, mais je n'aurais pas pu préparer mon contenu à l'avance facilement
# Donc j'utiliser VSCode Rest Client https://github.com/Huachao/vscode-restclient (et vous aussi)

# C'est quoi une API ? (pas seulement un truc qu'on trouve sur https://publicapis.io/ ou https://apislist.com/apis - qui est mieux)
# Un truc qui répond quand on l'appelle.
# Pour avoir tous les pays

GET https://restcountries.com/v3.1/all

### OK, c'est un peu gros, donc je vais juste récupérer les informations sur la France

GET https://restcountries.com/v3.1/name/France

### Vous avez vu qu'il y a la lattitude et la longitude ?
### On peut utiliser cette info dans d'autres apis (par exemple celle qui nous permet de récupérer la météo)

GET https://api.open-meteo.com/v1/forecast?latitude=46&longitude=é&current=temperature_2m,wind_speed_10m&hourly=temperature_2m,relative_humidity_2m,wind_speed_10m"

### Tiens, c'est quoi ces histoires de code http ?

GET https://http.dog/400

### Plus sérieusement, la wikipedia est notre amie

https://fr.wikipedia.org/wiki/Liste_des_codes_HTTP?useskin=vector

### Cela dit, il y a des apis plus intéressantes ailleurs
### Par exemple l'api des espèces menacées https://www.iucnredlist.org/
### Oh mais c'est quoi cette histoire de token ?

### Allons voir comment exécuter une requête dans la doc de l'api https://api.iucnredlist.org/api-docs/index.html

### Donc maintenant qu'on a une belle API bien complète, on va développer une application
### qui, à partir d'un pays, donne la liste des noms d'espcèes menacées triées par années.

GET https://api.iucnredlist.org/api/v4/countries/FR
accept: application/json
Authorization: mp6cgxGRGUT6EZ6jbS6dEBsWAsRYGvSscvQR

### Et on récupère une espèce

GET https://api.iucnredlist.org/api/v4/assessment/500969
accept: application/json
Authorization: mp6cgxGRGUT6EZ6jbS6dEBsWAsRYGvSscvQR