name: Run qualscan on commit on main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.19.1]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g npm@9.2.0
      - run: npm ci
      - run: npm run linter

      - name: Run the qualscan tool
        run: |
          npm install qualscan -g
          qualscan --scripts

      - name: Run the tests
        run: npm run test
